sudo: required
dist: bionic
language: node_js
env:
  - CXX="g++-7"
node_js:
  - "12"
  - "11"


addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7

